server:
  ip: localhost
  #port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/warehouse?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 1996100670
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: localhost
    port: 6379
    # 如果有密码，请取消注释并替换为你的密码
    password: 1996100670
  jmx:
    enabled: false
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 日志
    map-underscore-to-camel-case: true  # 开启驼峰命名
mybatis:
  mapper-locations: classpath*:/mapper/**/*.xml # 扫描所有mybatis的xml文件

